trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureContainerApps@1
    inputs:
      azureSubscription: '91b277db-132d-41ed-beda-d2effc05ba4a'
      containerAppName: 'rpg-app'
      resourceGroup: 'project2025'
      imageToDeploy: 'https://hub.docker.com/repository/docker/bunchieldz/flask/tags/1.0/' 